name: Go
on:
  push:
env:
  GO_VERSION: "^1.20.4"
  GOLANGCI_LINT_VERSION: "v1.50.1"
  REGISTRY: registry.uw.systems
  IMAGE_NAME: "onboarding-cknightonpullin"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup private repo access
        run: git config --global url."https://${{ secrets.DEPLOY_GITHUB_USER }}:${{ secrets.DEPLOY_GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: Setup Go
        uses: utilitywarehouse/actions-go/setup@main
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          skip-go-installation: true
      - name: Test
        run: make all
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          build-args: |
            SERVICE=${{ env.IMAGE_NAME }}
            GITHUB_TOKEN=${{ secrets.DEPLOY_GITHUB_TOKEN }}
            GITHUB_USER=${{ secrets.DEPLOY_GITHUB_USER }}
          tags: ${{ env.REGISTRY }}/onboarding/${{ env.IMAGE_NAME }}:${{ github.sha }}
          push: true
